In [2]:
import pandas as pd

In [3]:
s = pd.Series([1,5,9,7,6,5])
s

0    1
1    5
2    9
3    7
4    6
5    5
dtype: int64

In [4]:
s = pd.Series([1,5,9,7,6,5],dtype='int8')
s

0    1
1    5
2    9
3    7
4    6
5    5
dtype: int8

In [5]:

s.sum()

33

In [6]:
s.dtype

dtype('int8')

In [7]:
s.shape

(6,)

In [8]:
s.size

6

In [9]:
s = pd.Series([1,5,9,7,6,5], index= list('abcdef'))
s

a    1
b    5
c    9
d    7
e    6
f    5
dtype: int64

In [10]:
s[0]

1

In [11]:
s['a']

1

In [12]:
s = pd.Series(1,index= range(1,11))
s

1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
dtype: int64

In [13]:
s[5:] = 0

In [14]:
s

1     1
2     1
3     1
4     1
5     1
6     0
7     0
8     0
9     0
10    0
dtype: int64

In [15]:
s = pd.Series(['abc','xyz','pqr','abc','xyz','pqr','abc','xyz','pqr','ddd'],index= range(1,11))
s

1     abc
2     xyz
3     pqr
4     abc
5     xyz
6     pqr
7     abc
8     xyz
9     pqr
10    ddd
dtype: object

In [16]:
s.replace({'abc':9, 'xyz':0,'pqr':1,'ddd':8})

1     9
2     0
3     1
4     9
5     0
6     1
7     9
8     0
9     1
10    8
dtype: int64

In [17]:
s = s.replace({'abc':9, 'xyz':0,'pqr':1,'ddd':8})

In [18]:
s[: , None]

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  """Entry point for launching an IPython kernel.


array([[9],
       [0],
       [1],
       [9],
       [0],
       [1],
       [9],
       [0],
       [1],
       [8]])

In [19]:
import numpy as np


In [20]:
x = np.array(s)
x

array([9, 0, 1, 9, 0, 1, 9, 0, 1, 8])

In [21]:
x = np.random.randint(11,99,size=(10,3))

In [22]:
df = pd.DataFrame(x)
df

0   1   2
0  59  64  37
1  92  16  74
2  43  62  85
3  56  75  58
4  16  27  56
5  72  84  19
6  17  37  97
7  49  85  76
8  80  53  75
9  20  44  74

In [23]:
df = pd.DataFrame(x,columns=['A','B','C'])
df

A   B   C
0  59  64  37
1  92  16  74
2  43  62  85
3  56  75  58
4  16  27  56
5  72  84  19
6  17  37  97
7  49  85  76
8  80  53  75
9  20  44  74

In [24]:
df.columns = ['one','two','three']

In [25]:
df

one  two  three
0   59   64     37
1   92   16     74
2   43   62     85
3   56   75     58
4   16   27     56
5   72   84     19
6   17   37     97
7   49   85     76
8   80   53     75
9   20   44     74

In [26]:
df['one']

0    59
1    92
2    43
3    56
4    16
5    72
6    17
7    49
8    80
9    20
Name: one, dtype: int64

In [27]:
df.dtypes

one      int64
two      int64
three    int64
dtype: object

In [28]:
df.shape

(10, 3)

In [29]:
df.one

0    59
1    92
2    43
3    56
4    16
5    72
6    17
7    49
8    80
9    20
Name: one, dtype: int64

In [30]:
df[['two','one','three']]

two  one  three
0   64   59     37
1   16   92     74
2   62   43     85
3   75   56     58
4   27   16     56
5   84   72     19
6   37   17     97
7   85   49     76
8   53   80     75
9   44   20     74

In [31]:
df['four'] = round((df['one']*df['two'])/df['three'],2)

In [32]:
df

one  two  three    four
0   59   64     37  102.05
1   92   16     74   19.89
2   43   62     85   31.36
3   56   75     58   72.41
4   16   27     56    7.71
5   72   84     19  318.32
6   17   37     97    6.48
7   49   85     76   54.80
8   80   53     75   56.53
9   20   44     74   11.89

In [33]:
df.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [34]:
df2 = df[['one', 'two', 'three']]

In [35]:
# df2.loc[0,0]= 999

In [36]:
# df2

In [37]:
# df

In [38]:
df.drop('four',axis=1,inplace=True)

In [39]:
df.T

0   1   2   3   4   5   6   7   8   9
one    59  92  43  56  16  72  17  49  80  20
two    64  16  62  75  27  84  37  85  53  44
three  37  74  85  58  56  19  97  76  75  74

In [40]:
df.iloc[5]

one      72
two      84
three    19
Name: 5, dtype: int64

In [41]:
df.iloc[0:5]

one  two  three
0   59   64     37
1   92   16     74
2   43   62     85
3   56   75     58
4   16   27     56

In [42]:
df.iloc[0:5, 'one']

ValueError: ignored

In [45]:
df.iloc[0:5, 0]

0    59
1    92
2    43
3    56
4    16
Name: one, dtype: int64

In [46]:
df.iloc[0:5, [0,1]]

one  two
0   59   64
1   92   16
2   43   62
3   56   75
4   16   27

In [47]:
df.loc[0:5, [0,1]]

KeyError: ignored

In [48]:
df.loc[0:5, ['one','two']]

one  two
0   59   64
1   92   16
2   43   62
3   56   75
4   16   27
5   72   84

In [49]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [50]:
len(df)

10

In [51]:
df.iloc[-1]

one      20
two      44
three    74
Name: 9, dtype: int64

In [52]:
df.loc[0,'one'] = 99

In [53]:
df

one  two  three
0   99   64     37
1   92   16     74
2   43   62     85
3   56   75     58
4   16   27     56
5   72   84     19
6   17   37     97
7   49   85     76
8   80   53     75
9   20   44     74

In [54]:
df.loc[100] = [99,99,99]

In [55]:
df

one  two  three
0     99   64     37
1     92   16     74
2     43   62     85
3     56   75     58
4     16   27     56
5     72   84     19
6     17   37     97
7     49   85     76
8     80   53     75
9     20   44     74
100   99   99     99

In [56]:
df['cat']= 'Abc'

In [57]:
df

one  two  three  cat
0     99   64     37  Abc
1     92   16     74  Abc
2     43   62     85  Abc
3     56   75     58  Abc
4     16   27     56  Abc
5     72   84     19  Abc
6     17   37     97  Abc
7     49   85     76  Abc
8     80   53     75  Abc
9     20   44     74  Abc
100   99   99     99  Abc

In [58]:
df.cat = df.cat.replace({'Abc':9})

In [59]:
df

one  two  three  cat
0     99   64     37    9
1     92   16     74    9
2     43   62     85    9
3     56   75     58    9
4     16   27     56    9
5     72   84     19    9
6     17   37     97    9
7     49   85     76    9
8     80   53     75    9
9     20   44     74    9
100   99   99     99    9

In [60]:
list('abcdefghijk')

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k']

In [61]:
df.ind = list('abcdefghijk')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  """Entry point for launching an IPython kernel.


In [62]:
df['ind'] = list('abcdefghijkl')

ValueError: ignored

In [63]:
df

one  two  three  cat
0     99   64     37    9
1     92   16     74    9
2     43   62     85    9
3     56   75     58    9
4     16   27     56    9
5     72   84     19    9
6     17   37     97    9
7     49   85     76    9
8     80   53     75    9
9     20   44     74    9
100   99   99     99    9

In [64]:
df.set_index('ind',inplace=True)

KeyError: ignored

In [65]:
df

one  two  three  cat
0     99   64     37    9
1     92   16     74    9
2     43   62     85    9
3     56   75     58    9
4     16   27     56    9
5     72   84     19    9
6     17   37     97    9
7     49   85     76    9
8     80   53     75    9
9     20   44     74    9
100   99   99     99    9

In [66]:
df.iloc[0]

one      99
two      64
three    37
cat       9
Name: 0, dtype: int64

In [67]:
df.iloc['a']

TypeError: ignored

In [68]:
df.loc['a']

KeyError: ignored

In [69]:
df.reset_index(inplace=True)

In [70]:
df.values

array([[  0,  99,  64,  37,   9],
       [  1,  92,  16,  74,   9],
       [  2,  43,  62,  85,   9],
       [  3,  56,  75,  58,   9],
       [  4,  16,  27,  56,   9],
       [  5,  72,  84,  19,   9],
       [  6,  17,  37,  97,   9],
       [  7,  49,  85,  76,   9],
       [  8,  80,  53,  75,   9],
       [  9,  20,  44,  74,   9],
       [100,  99,  99,  99,   9]])

In [71]:
df.sample(2)

index  one  two  three  cat
5      5   72   84     19    9
7      7   49   85     76    9

In [72]:
df.head(2)

index  one  two  three  cat
0      0   99   64     37    9
1      1   92   16     74    9

In [73]:
df.tail(2)

index  one  two  three  cat
9       9   20   44     74    9
10    100   99   99     99    9

In [74]:
df

index  one  two  three  cat
0       0   99   64     37    9
1       1   92   16     74    9
2       2   43   62     85    9
3       3   56   75     58    9
4       4   16   27     56    9
5       5   72   84     19    9
6       6   17   37     97    9
7       7   49   85     76    9
8       8   80   53     75    9
9       9   20   44     74    9
10    100   99   99     99    9